---
## Install/configure for Rhel 6 and 7

# Install
- name: Install lsync from repo for Rhel6+
  yum: name=lsyncd state=present

# Copy configuation
- name: Configure lsync for Rhel6+
  template: src=lsyncd.conf.j2
        dest=/etc/lsyncd.conf
        owner=root
        group=root
        mode=0644

