---

# Include the lsync slaves file
# This should be an array of slave ips/hosts. Ansible will only add this to the
# config file, but not install ssh keys on the slave servers. That is left for
# nova to handle.
# Example slaves.yml:
# ---
# slaves:
# - 192.168.3.2
# - 192.168.3.3
- name: Read in lsync slaves
  include_vars: slaves.yml

- name: Create lsyncd log directory
  file: path=/var/log/lsyncd state=directory

# For Redhat/Centos 6 or 7
- when: ansible_os_family == 'RedHat' and
        (ansible_distribution_major_version == '6' or
         ansible_distribution_major_version == '7')
  include: el67.yml

# For Ubuntu14.04 and Debian 8
- when: (ansible_distribution == "Ubuntu" and
        ansible_distribution_version == "14.04") or
        (ansible_distribution == "Debian" and
         ansible_distribution_major_version == "8")
  include: ubuntu1404.yml

# For el5, debian7, and ubuntu12.04
- when: (ansible_os_family == 'RedHat' and
         ansible_distribution_major_version == '5') or
        (ansible_distribution == "Ubuntu" and
         ansible_distribution_version == "12.04") or
        (ansible_distribution == "Debian" and
         ansible_distribution_major_version == "7")
  include: source.yml

