---

- name: Install lsyncd dependencies for Redhat
  when: ansible_os_family == 'Redhat'
  yum: name={{item}} state=present
  with_items:
   - lua
   - lua-devel
   - pkgconfig
   - gcc
   - asciidoc
   - make

- name: Install lsyncd dependencies for Debian
  when: ansible_os_family == 'Debian'
  apt: name={{item}} state=present
  with_items:
   - lua5.1
   - liblua5.1-dev
   - pkg-config
   - rsync
   - asciidoc
   - make

- name: Copy lsyncd source
  copy: src=lsyncd-2.1.5.tar.gz dest=/usr/local/src

- name: Copy lsyncd build script
  copy: src=lsyncd-build.sh dest=/root/lsyncd-build.sh mode=0775

- name: Build lsyncd
  shell: /root/lsyncd-build.sh creates=/usr/local/bin/lsyncd

- name: Configure lsyncd for source install
- file: path=/var/log/lsyncd state=directory
- template: src=lsyncd.conf.j2
        dest=/etc/lsyncd.conf
        owner=root
        group=root
        mode=0644

- name: Install lsyncd init script for Debian
  when: ansible_os_family == 'Debian'
  copy: src=lsyncd-init-el path=/etc/init.d/lsyncd 

- name: Install lsyncd init script for Redhat
  when: ansible_os_family == 'Redhat'
  copy: src=lsyncd-init-deb path=/etc/init.d/lsyncd
