---
## Install/configure for Ubuntu14.04

# Install
- name: Install lsync from repo for Ubuntu14.04
  apt: name=lsyncd state=present

# Configure
- name: Create lsyncd conf directory
  file: path=/etc/lsyncd state=directory
- name: Configure lsync for Ubuntu14.04
  template: src=lsyncd.conf.j2
        dest=/etc/lsyncd/lsyncd.conf.lua
        owner=root
        group=root
        mode=0644
